### PR TITLE
 Make enableSeveralDrivers usable

### PR DESCRIPTION
**Pull request by mrbear**
I have modified ContaractorMod to make enableSeveralDrivers usable.

Solves problems with duplicate drivers in cab and removal of visual driver on first driver exit. Also enables additional drivers to leave with AI active as long as one driver remains in the cab.

Feel free to use the code if you like and modify it in any way you see fit.

### CODE REVIEW

**Comment by yumi-modding** [comment]
Thanks for the changes. I will see how to integrate it since I made some code I've not pushed yet on github.

**Comment by mrbear** [comment]
First of all, thanks for a brilliant mod. 

I have done some more changes today.
I have characters with consistent appearance inside and outside of vehicles with configuration for male/female and color in the xml. I have also fixed the idle animation when displayOnFootWorker is used. 

I just want to fix some bugs and the support for visual passengers, then I can make a pull request so you can see if any of it is interesting for the official version. I made the changes because I like the mod and want the functionality my self but if you find parts of them useful feel free to take the parts you like. 

Ps. The code that In the pull request have a problem that drivers in a vehicle when loading a savegame is invisible until you exit and enter again. Will sort that as well.

**Comment by yumi-modding** [comment]
Thanks a lot :-)
That would be great since this is what I was trying to achieve.
Feel free to share the code even if some bugs might remain since nobody uses this repo I guess, except maybe the zip file.

**Comment by mrbear** [comment]
This code should be in a rather stable state.

Known issues:

- Driver invisible after loading savegame. -- Will try to fix that when I implement passengers, needs to rewrite that code anyway.
- Follow me and courseplay might need some wrapping similar to what I did for the helper to avoid them changing the driver.
- Passengers are invisible.

**Pull request merged**
